var CONFIG = {
	DEV_MODE : false,
	DISC_BLOW_DELAY : 500,
	DEFAULT_EVENT_DELAY : 5,
	CELL_MARGIN : 4,
	CELL_SIZE : 50,
	HIGHLIGHT_STROKE_WIDTH : 2,
	HIGHLIGHT_STROKE : 'black',
	HIGHLIGHT_PERIOD_MILLIS : 400,
	CELL_SIZE : 50,
	CELL_MARGIN: 4,
	GRID_LINE_WIDTH : 1,
	GRID_LINE_COLOR : 'black'
	, GAME_SIZE_UPPER_BOUND : 20
	, MAX_DISCS_TO_NEW_LINE : 7
	, SCORE_MULTIPLIER : 5
	
};